#!/bin/bash -e

ZOOKEEPER=localhost:2181

create_topic ()
{
  $KAFKA_HOME/bin/kafka-topics.sh --delete --if-exists --zookeeper $ZOOKEEPER --topic $1
  $KAFKA_HOME/bin/kafka-topics.sh --create --zookeeper $ZOOKEEPER --replication-factor 1 --partitions $2 --topic $1
}

echo "-----------------"
echo " Creating topics "
echo "-----------------"
echo
create_topic ProductOrderCreated 3
create_topic ProductOrderUpdated 3
create_topic BSSProductOrder 3
create_topic BSSOrganization 3
create_topic organizationCreationNotification 3

echo
echo "-----------------"
echo " List all topics "
echo "-----------------"
echo
$KAFKA_HOME/bin/kafka-topics.sh --list --zookeeper $ZOOKEEPER
