#!/bin/bash

USER_NAME=${USER_NAME:='root'}
USER_PASSWORD=${USER_PASSWORD:='control123!'}
MYSQL_PORT=3306

# Make sure that the user and password is "root" and "control123!" otherwise you should change it.
# Make sure the names of the schemas are correct otherwise you should change it.
echo 'Creating databases for VEEA'
mysql --host 127.0.0.1 --port $MYSQL_PORT -u$USER_NAME -p$USER_PASSWORD -e "create schema if not exists acl_db; create schema if not exists authdb; create schema if not exists bootstrap_db; create schema if not exists bss_oss_transactions; create schema if not exists bss_oss_users; create schema if not exists ccenter_db; create schema if not exists certificate_db; create schema if not exists enrollment_db; create schema if not exists ifree_veea; create schema if not exists maxdb; create schema if not exists maxIntranet; create schema if not exists msadb; create schema if not exists pocdb; create schema if not exists testdb; create schema if not exists auth_keycloak;"
echo