#!/bin/bash

USER_NAME=${USER_NAME:='root'}
USER_PASSWORD=${USER_PASSWORD:='control123!'}
MYSQL_PORT=3306

# Make sure that the user and password is "root" and "control123!" otherwise you should change it.
# Make sure the names of the databases are correct otherwise you should change it.
echo 'Creating databases for VEEA'
docker exec veea-mysql mysql --host 127.0.0.1 --port $MYSQL_PORT -u$USER_NAME -p$USER_PASSWORD -e "create database if not exists acl_db; create database if not exists authdb; create database if not exists bootstrap_db; create database if not exists bss_oss_transactions; create database if not exists bss_oss_users; create database if not exists ccenter_db; create database if not exists certificate_db; create database if not exists enrollment_db; create database if not exists ifree_veea; create database if not exists maxdb; create database if not exists maxIntranet; create database if not exists msadb; create database if not exists pocdb; create database if not exists testdb; create database if not exists keycloak; create database if not exists auth_keycloak;"
echo