#!/bin/bash -e

ZOOKEEPER=zookeeper:2181

create_topic ()
{
  docker exec kafka /opt/kafka_2.11-0.8.2.1/bin/kafka-topics.sh --delete --zookeeper $ZOOKEEPER --topic $1
  docker exec kafka /opt/kafka_2.11-0.8.2.1/bin/kafka-topics.sh --create --zookeeper $ZOOKEEPER --replication-factor 1 --partitions $2 --topic $1
}

echo "-----------------"
echo " Creating topics "
echo "-----------------"
echo
create_topic BSSOrganization 3
create_topic BOSSOrganization 3
create_topic BSSProductOrder 3
create_topic ProductOrderCreated 3
create_topic organizationCreationNotification 3
create_topic enrollment-device-status 3
create_topic enrollmentActionNotification 3
create_topic Notification 3
create_topic BOSSTransactionLog 3
create_topic transactionTopic 3
create_topic billingEvent 3
create_topic BOSSCitconTransactionLog 3
create_topic eventManagementTopic 3
create_topic organizationUpdate 3

echo
echo "-----------------"
echo " List all topics "
echo "-----------------"
echo
docker exec kafka /opt/kafka_2.11-0.8.2.1/bin/kafka-topics.sh --list --zookeeper $ZOOKEEPER
