#!/bin/bash -e

export KEYCLOAK_HOME=/opt/jboss/keycloak
export KEYCLOAK_DEPLOYMENTS=/opt/jboss/keycloak/standalone/deployments

docker cp $MAX_SRC_HOME/max-dev-bin/keycloak/dependencies/jbcrypt/jbcrypt-0.4.jar keycloak:${KEYCLOAK_HOME}/bin
docker exec -ti keycloak $KEYCLOAK_HOME/bin/jboss-cli.sh --command="module add --name=org.mindrot.jbcrypt --resources=${KEYCLOAK_HOME}/bin/jbcrypt-0.4.jar"
docker cp $MAX_SRC_HOME/veea-spi-password-hashing/target/veea-spi-password-hashing-1.0.1.jar keycloak:${KEYCLOAK_DEPLOYMENTS}