#!/bin/bash -e

export KEYCLOAK_HOME=/opt/jboss/keycloak
export KEYCLOAK_DEPLOYMENTS=/opt/jboss/keycloak/standalone/deployments

#sudo cp -rf $MAX_HOME/keycloak/dependencies/jbcrypt/module.xml ~/docker-volumes/keycloak-data/dependencies/jbcrypt/
#sudo cp -rf $MAX_HOME/keycloak/dependencies/jbcrypt/jbcrypt-0.4.jar ~/docker-volumes/keycloak-data/dependencies/jbcrypt/
#sudo cp -rf $MAX_HOME/keycloak/deployments/keycloak-bcrypt-1.0.0.jar ~/docker-volumes/keycloak-data/deployments/

docker cp $MAX_HOME/keycloak/dependencies/jbcrypt/jbcrypt-0.4.jar keycloak:${KEYCLOAK_HOME}/bin
docker exec -ti keycloak $KEYCLOAK_HOME/bin/jboss-cli.sh --command="module add --name=org.mindrot.jbcrypt --resources=${KEYCLOAK_HOME}/bin/jbcrypt-0.4.jar"
docker cp $MAX_HOME/keycloak/deployments/veea-spi-password-hashing-1.0.0.jar keycloak:${KEYCLOAK_DEPLOYMENTS}