#!/bin/bash

BACKUP_HOME=${BACKUP_HOME:='/Users/jantezana/Desktop/Mojix/Veea/Backups/mysql-data/restore_backup'}
USER_NAME=${USER_NAME:='root'}
USER_PASSWORD=${USER_PASSWORD:='control123!'}
MYSQL_PORT=3306

echo "BACKUP_HOME: $BACKUP_HOME"
echo "USER_NAME: $USER_NAME"
echo "USER_PASSWORD: $USER_PASSWORD"

echo "start restore acl_db"
docker exec -i veea-mysql mysql --host 127.0.0.1 --port $MYSQL_PORT -u$USER_NAME -p$USER_PASSWORD acl_db < $BACKUP_HOME/acl_db/MySQL.sql
echo "end restore"
echo "start restore authdb"
docker exec -i veea-mysql mysql --host 127.0.0.1 --port $MYSQL_PORT -u$USER_NAME -p$USER_PASSWORD authdb < $BACKUP_HOME/authdb/MySQL.sql
echo "end restore"
echo "start restore bootstrap_db"
docker exec -i veea-mysql mysql --host 127.0.0.1 --port $MYSQL_PORT -u$USER_NAME -p$USER_PASSWORD bootstrap_db < $BACKUP_HOME/bootstrap_db/MySQL.sql
echo "end restore"
echo "start restore bss_oss_transactions"
docker exec -i veea-mysql mysql --host 127.0.0.1 --port $MYSQL_PORT -u$USER_NAME -p$USER_PASSWORD bss_oss_transactions < $BACKUP_HOME/bss_oss_transactions/MySQL.sql
echo "end restore"
echo "start restore bss_oss_users"
docker exec -i veea-mysql mysql --host 127.0.0.1 --port $MYSQL_PORT -u$USER_NAME -p$USER_PASSWORD bss_oss_users < $BACKUP_HOME/bss_oss_users/MySQL.sql
echo "end restore"
echo "start restore ccenter_db"
docker exec -i veea-mysql mysql --host 127.0.0.1 --port $MYSQL_PORT -u$USER_NAME -p$USER_PASSWORD ccenter_db < $BACKUP_HOME/ccenter_db/MySQL.sql
echo "end restore"
echo "start restore certificate_db"
docker exec -i veea-mysql mysql --host 127.0.0.1 --port $MYSQL_PORT -u$USER_NAME -p$USER_PASSWORD certificate_db < $BACKUP_HOME/certificate_db/MySQL.sql
echo "end restore"
echo "start restore enrollment_db"
docker exec -i veea-mysql mysql --host 127.0.0.1 --port $MYSQL_PORT -u$USER_NAME -p$USER_PASSWORD enrollment_db < $BACKUP_HOME/enrollment_db/MySQL.sql
echo "end restore"
echo "start restore ifree_veea"
docker exec -i veea-mysql mysql --host 127.0.0.1 --port $MYSQL_PORT -u$USER_NAME -p$USER_PASSWORD ifree_veea < $BACKUP_HOME/ifree_veea/MySQL.sql
echo "end restore"
echo "start restore maxdb"
docker exec -i veea-mysql mysql --host 127.0.0.1 --port $MYSQL_PORT -u$USER_NAME -p$USER_PASSWORD maxdb < $BACKUP_HOME/maxdb/MySQL.sql
echo "end restore"
echo "start restore maxIntranet"
docker exec -i veea-mysql mysql --host 127.0.0.1 --port $MYSQL_PORT -u$USER_NAME -p$USER_PASSWORD maxIntranet < $BACKUP_HOME/maxintranet/MySQL.sql
echo "end restore"
echo "start restore msadb"
docker exec -i veea-mysql mysql --host 127.0.0.1 --port $MYSQL_PORT -u$USER_NAME -p$USER_PASSWORD msadb < $BACKUP_HOME/msa/MySQL.sql
echo "end restore"
echo "start restore pocdb"
docker exec -i veea-mysql mysql --host 127.0.0.1 --port $MYSQL_PORT -u$USER_NAME -p$USER_PASSWORD pocdb < $BACKUP_HOME/pocdb/MySQL.sql
echo "end restore"
echo "start restore testdb"
docker exec -i veea-mysql mysql --host 127.0.0.1 --port $MYSQL_PORT -u$USER_NAME -p$USER_PASSWORD testdb < $BACKUP_HOME/testdb/MySQL.sql
echo "end restore"