#!/bin/bash -e
echo
echo "### removing mysql"

# delete mysql if exists
if ! [[ -z `docker inspect --format="{{ .State.Running }}" mysql` ]]; then
  docker rm -f mysql
fi

echo
echo "### running mysql"
echo

MAX_NETWORK=${MAX_NETWORK:='vizix-network'}
MAX_MYSQL_HOST=${MAX_MYSQL_HOST:='172.18.0.10'}
echo "MAX_NETWORK: $MAX_NETWORK"
echo "MAX_MYSQL_HOST: $MAX_MYSQL_HOST"
echo

docker run -d --name mysql -h mysql \
--network $MAX_NETWORK \
--ip $MAX_MYSQL_HOST \
-p 3306:3306 \
-e MYSQL_DATABASE=riot_main \
-e MYSQL_ROOT_PASSWORD=control123! \
-v ~/docker-volumes/mysql-data:/var/lib/mysql \
-v ~/docker-volumes/mysql-tmp:/tmp/mysql \
mysql:5.7 \
--max_allowed_packet=1024M \
--max_connections=1500 \
--query_cache_size=0 \
--interactive_timeout=900 \
--wait_timeout=900 \
--lower_case_table_names=1 \
--net_write_timeout=3600 \
--net_read_timeout=3600 \
--connect_timeout=900 \
--secure-file-priv=""
