#!/bin/bash

echo "### Compiling party management backend ###"
cd $MAX_SRC_HOME/party-management-backend
pwd
git stash
git pull
git stash pop
sbt clean compile

echo "## Starting party management backend ##"
sbt clean compile run -Dhttp.port=9010