#!/bin/bash -e
echo
echo "### removing elasticsearch_new"

# delete mysql if exists
if ! [[ -z `docker inspect --format="{{ .State.Running }}" elasticsearch_new` ]]; then
  docker rm -f elasticsearch_new
fi

echo
echo "### running elasticsearch_new"
echo

MAX_NETWORK=${MAX_NETWORK:='max-network'}
MAX_ELASTIC_SEARCH_HOST=${MAX_ELASTIC_SEARCH_HOST:='172.18.0.20'}
echo "MAX_NETWORK: $MAX_NETWORK"
echo "MAX_ELASTIC_SEARCH_HOST: $MAX_ELASTIC_SEARCH_HOST"
echo

docker run -d --name elasticsearch_new -h elasticsearch_new \
--network $MAX_NETWORK \
--ip $MAX_ELASTIC_SEARCH_HOST \
-p 9200:9200 \
-p 9300:9300 \
-v ~/docker-volumes/elasticsearch-data:/usr/share/elasticsearch/data \
elasticsearch