#!/bin/bash

echo "### Compiling product order frontend ###"
cd $MAX_SRC_HOME/product-order-frontend
pwd
yarn

echo "### Installing dependencies in the server ###"
cd $MAX_SRC_HOME/product-order-frontend/server
yarn install

echo "### Installing dependencies in the client ###"
cd $MAX_SRC_HOME/product-order-frontend/client
yarn install

echo "## Initializing authentication frontend ##"
cd $MAX_SRC_HOME/product-order-frontend
yarn start