#!/bin/bash -e
echo
echo "### removing kafka-zookeeper"

# delete kafka-zookeeper if exists
if ! [[ -z `docker inspect --format="{{ .State.Running }}" kafka-zookeeper` ]]; then
  docker rm -f kafka-zookeeper
fi

echo
echo "### running kafka-zookeeper"
echo

MAX_NETWORK=${MAX_NETWORK:='max-network'}
MAX_KAFKA_ZOOKEEPER_HOST=${MAX_KAFKA_ZOOKEEPER_HOST:='172.18.0.80'}
LOCAL_IP_ADDRESS=$(ipconfig getifaddr en0)
echo "MAX_NETWORK: $MAX_NETWORK"
echo "MAX_KAFKA_ZOOKEEPER_HOST: $MAX_KAFKA_ZOOKEEPER_HOST"
echo "LOCAL_IP_ADDRESS: $LOCAL_IP_ADDRESS"
echo

docker run -d --name kafka-zookeeper -h kafka-zookeeper \
--network $MAX_NETWORK \
--ip $MAX_KAFKA_ZOOKEEPER_HOST \
-p 2181:2181 \
-p 9092:9092 \
--env ADVERTISED_HOST=$LOCAL_IP_ADDRESS \
--env ADVERTISED_PORT=9092 \
spotify/kafka

sleep 5s
create-topics