#!/bin/bash -e
echo
echo "### removing mysql-msa"

# delete mysql if exists
if ! [[ -z `docker inspect --format="{{ .State.Running }}" mysql-msa` ]]; then
  docker rm -f mysql-msa
fi

echo
echo "### running mysql-msa"
echo

MAX_NETWORK=${MAX_NETWORK:='max-network'}
MAX_MYSQL_MSA_HOST=${MAX_MYSQL_MSA_HOST:='172.18.0.12'}
echo "MAX_NETWORK: $MAX_NETWORK"
echo "MAX_MYSQL_MSA_HOST: $MAX_MYSQL_MSA_HOST"
echo

docker run -d --name mysql-msa -h mysql-msa \
--network $MAX_NETWORK \
--ip $MAX_MYSQL_MSA_HOST \
-p 3308:3306 \
-e MYSQL_DATABASE=maxdb \
-e MYSQL_ROOT_PASSWORD=admin \
-e MYSQL_USER=playservices \
-e MYSQL_PASSWORD=play \
-v ~/docker-volumes/mysql-data-msa:/var/lib/mysql \
-v ~/docker-volumes/mysql-tmp-msa:/tmp/mysql \
mysql:5.7 \
--max_allowed_packet=1024M \
--max_connections=1500 \
--query_cache_size=0 \
--interactive_timeout=900 \
--wait_timeout=900 \
--lower_case_table_names=1 \
--net_write_timeout=3600 \
--net_read_timeout=3600 \
--connect_timeout=900 \
--secure-file-priv=""
