#!/bin/bash -e
echo
echo "### removing mysql-max"

# delete mysql if exists
if ! [[ -z `docker inspect --format="{{ .State.Running }}" mysql-max` ]]; then
  docker rm -f mysql-max
fi

echo
echo "### running mysql-max"
echo

MAX_NETWORK=${MAX_NETWORK:='max-network'}
MAX_MYSQL_MAX_HOST=${MAX_MYSQL_MAX_HOST:='172.18.0.11'}
echo "MAX_NETWORK: $MAX_NETWORK"
echo "MAX_MYSQL_MAX_HOST: $MAX_MYSQL_MAX_HOST"
echo

docker run -d --name mysql-max -h mysql-max \
--network $MAX_NETWORK \
--ip $MAX_MYSQL_MAX_HOST \
-p 3307:3306 \
-e MYSQL_DATABASE=maxdb \
-e MYSQL_ROOT_PASSWORD=admin \
-e MYSQL_USER=playservices \
-e MYSQL_PASSWORD=play \
-v ~/docker-volumes/mysql-data-max:/var/lib/mysql \
-v ~/docker-volumes/mysql-tmp-max:/tmp/mysql \
mysql:5.6.33 \
--max_allowed_packet=1024M \
--max_connections=1500 \
--query_cache_size=0 \
--interactive_timeout=900 \
--wait_timeout=900 \
--lower_case_table_names=1 \
--net_write_timeout=3600 \
--net_read_timeout=3600 \
--connect_timeout=900 \
--secure-file-priv=""
